changelog:
  categories:
    - title: ":boom: Breaking Changes"
      labels:
        - breaking-change

    - title: ":sparkles: New Features"
      labels:
        - enhancement

    - title: ":bug: Bug Fixes"
      labels:
        - bug

    - title: ":memo: Documentation"
      labels:
        - documentation

    - title: ":pushpin: Other Changes"
      labels:
        - "*"
